### -------------------------------read data in & prepare ----------------------------------------------------###

#controlBetaMatrix<-read.csv("/home/lbondhus/Desktop/PROJECTS/dmrscaler_simulation/intermediate_data/Control_Beta_Matrix.csv",row.names = 1)
#controlCGlocs<-read.csv("/home/lbondhus/Desktop/PROJECTS/dmrscaler_simulation/intermediate_data/Control_CG_locs.csv",row.names = 1)
#controlPhenoData<-read.csv("/home/lbondhus/Desktop/PROJECTS/dmrscaler_simulation/intermediate_data/Control_Pheno_Data.csv",row.names=1)
#subset the control beta matrix for cpgs from chr5
#controlCGlocs<-controlCGlocs[controlCGlocs$V3=="chr5",]
#controlBetaMatrix<-controlBetaMatrix[rownames(controlBetaMatrix)%in%controlCGlocs$V1,]

###---------------- given a beta matrix of control patients, divide into two groups randomly -----------------###
#given:
#a df containing the beta values from all patients to be considered (rownames=CpG sites, colnames=Pt IDs)
#return:
#a df that has the samples randomly divided into 2 groups, A or Aprime 
randomizeTwoGroups<-function(betaMatrix){
  patientDesign<-data.frame(matrix(nrow=ncol(betaMatrix),ncol=2))
  colnames(patientDesign)<-c("group","sampleID")
  if(ncol(betaMatrix)%%2==0){
    coordinatesA<-sample(1:ncol(betaMatrix),ncol(betaMatrix)/2,replace=FALSE)
    patientDesign[1:(ncol(betaMatrix)/2),"group"]<-"A"
    patientDesign[1:(ncol(betaMatrix)/2),"sampleID"]<-colnames(betaMatrix)[coordinatesA]
    patientDesign[(ncol(betaMatrix)/2+1):(ncol(betaMatrix)),"group"]<-"Aprime"
    patientDesign[(ncol(betaMatrix)/2+1):(ncol(betaMatrix)),"sampleID"]<-colnames(betaMatrix)[-coordinatesA]
    return(patientDesign)
  }
  else{#odd amount of samples
    #there are only 2 groups
    size<-c(
      floor(ncol(betaMatrix)/2),
      ncol(betaMatrix)-floor(ncol(betaMatrix)/2)
    )
    #randomly assign if A will be bigger or smaller size
    size<-size[sample(1:2,1,replace = FALSE)]
    coordinatesA<-sample(1:ncol(betaMatrix),size,replace=FALSE)
    patientDesign[1:size,"group"]<-"A"
    patientDesign[1:size,"sampleID"]<-colnames(betaMatrix)[coordinatesA]
    patientDesign[(size+1):(ncol(betaMatrix)),"group"]<-"Aprime"
    patientDesign[(size+1):(ncol(betaMatrix)),"sampleID"]<-colnames(betaMatrix)[-coordinatesA]
    return(patientDesign)
  }
}

###------------------- randomly get the DMRs (from promoter regions) ------------------------------------------------###
#leroy already subset this for chr5; how many unique promoter regions? 413 length(unique(promoterInfo$Islands_Name))

#given:
#x, promoter info dataframe (so this will work with promter info not just info for chr5)
#n, number of these promoter regions that should be randomly chosen 
#return:
#a subset of the prometer info df containing the randomly chosen promoter regions
randomizeSelectRegions<-function(x, n){
  # subset for promoter regions; could change this for any other regulatory feature, ask leroy
  x<-x[x$Regulatory_Feature_Group=="Promoter_Associated",]
  if(n<length(unique(x$Islands_Name))){
    regionNames<-unique(x$Islands_Name)
    regionNames<-regionNames[-which(regionNames=="")]
    randRegions<-sample(1:length(regionNames),n,replace = FALSE)
    regionNames<-regionNames[randRegions]
    x<-x[x$Islands_Name %in% regionNames,]
    return(x)
  }
  else{ #print an error message if n is greater than the amount promter regions
    print(paste0("n is too big; there are only ",length(unique(x$Islands_Name))," number of regions in this dataframe"))
    break
  }
}

###------------------- make a bed file from the DMRs ------------------------------------------------###
#given:
#a df generated by randomizeSelectRegions
#return:
#a bed-like df of the randomly selected regions,based on column, "Islands_Name". (if you want to output this as a bed file, write.table,sep="\t" header=FALSE)
bedForRegions<-function(randRegions){
  regions<-unique(randRegions$Islands_Name)
  bedFile<-data.frame(matrix(nrow = length(regions),ncol = 4))
  colnames(bedFile)<-c("islands_name","chr","start","stop")
  bedFile$islands_name<-regions
  bedFile$chr<-sub("\\:.*","",bedFile$islands_name)
  bedFile$start<-gsub(".*\\:(.+)\\-.*", "\\1",bedFile$islands_name)
  bedFile$stop<-sub(".*\\-","",bedFile$islands_name)
  return(bedFile)
}

###------------------- make a CpG table from the DMRs ------------------------------------------------###
#given:
#a df generated by randomizeSelectRegions
#return:
#a df that contains all the CpG sites+info for the randomly selected DMRs 
cpgTableForRegions<-function(randRegions){
  table<-dplyr::select(randRegions,Name,chr,pos,Islands_Name)
  return(table)
}

###------------------- inflate/deflate randomly selected regions by a given constant------------------------------------------------###
#given: 
#cpgTable from cpgTableForRegions fcn
#mu: coefficient to be added (assuming a positive mu now)
#betaMatrix: df or matrix (beta matrix) that the beta values of CPGs within selected regions should be inflated (or deflated if given a negative coeff)
#experiment design df from randomizeTwoGroups fcn 
#return:
#betaMatrix, a matrix type but inflated(or deflated) by mu at the randomly selected regions
alterByMu<-function(mu,betaMatrix,expDesign, cpgTable){
  for (i in unique(cpgTable$Islands_Name)) {
    #print(i)
    currentCpGtable<-cpgTable[cpgTable$Islands_Name==i,]
    if(nrow(currentCpGtable) <= 1){ next;}
    betaMatrix<-as.matrix(betaMatrix)
    
    avgBeta_A<-mean( betaMatrix[which(is.element(rownames(betaMatrix), rownames(currentCpGtable))),
                                which(is.element(colnames(betaMatrix), expDesign[expDesign$group=="A","sampleID"]))]  )

    avgBeta_Aprime<-mean( betaMatrix[which(is.element(rownames(betaMatrix), rownames(currentCpGtable))),
                                which(is.element(colnames(betaMatrix), expDesign[expDesign$group=="Aprime","sampleID"]))]  )
    
    if(avgBeta_A > avgBeta_Aprime){
      #add mu to A
      betaMatrix[which(rownames(betaMatrix)%in%rownames(currentCpGtable)),which(colnames(betaMatrix)%in%expDesign[expDesign$group=="A","sampleID"])]<-
        betaMatrix[which(rownames(betaMatrix)%in%rownames(currentCpGtable)),which(colnames(betaMatrix)%in%expDesign[expDesign$group=="A","sampleID"])]+mu
    }
    else{
      betaMatrix[which(rownames(betaMatrix)%in%rownames(currentCpGtable)),which(colnames(betaMatrix)%in%expDesign[expDesign$group=="Aprime","sampleID"])]<-
        betaMatrix[which(rownames(betaMatrix)%in%rownames(currentCpGtable)),which(colnames(betaMatrix)%in%expDesign[expDesign$group=="Aprime","sampleID"])]+mu
    }
  }
  #doesn't matter if values are greater than 1 or less than 0
  return(betaMatrix)
}
